### ISSUE TITLE
Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:testCompile (default-testCompile) on project simple-maven-project-with-tests: Fatal error compiling: 无效的目标版本： 1.7 -> [Help 1]

### ISSUE THREAD

**Issue by b3601993** [jglick/simple-maven-project-with-tests#2]
Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:testCompile (default-testCompile) on project simple-maven-project-with-tests: Fatal error compiling: 无效的目标版本： 1.7 -> [Help 1]
![jenkins1](https://user-images.githubusercontent.com/9765169/32717977-97f38a6a-c896-11e7-8729-8464e66784ea.png)
![jenkins2](https://user-images.githubusercontent.com/9765169/32717994-a2b3cb18-c896-11e7-9b47-bf1e9d137960.png)
![jenkins3](https://user-images.githubusercontent.com/9765169/32718010-ad386d32-c896-11e7-948c-5c795e27f2ae.png)

**I am running on Linux (/home/activemq/apache-maven-3.2.3/bin/mvn -B verify) No problem, but it is reported in jenkins**

![jenkins4](https://user-images.githubusercontent.com/9765169/32718181-3dad1ade-c897-11e7-8951-3736f85374d0.png)

why?

**Comment by jglick** [comment]
Not sure offhand; try using Java 8.
